<a href="https://colab.research.google.com/github/Tanishqkathed/Learning-Pandas/blob/main/labpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("car.csv")

In [9]:
df.groupby("Make")["MSRP"].max()

Make
Acura             156000
Alfa Romeo         68400
Aston Martin      320695
Audi              199900
BMW               141200
Bentley           363000
Bugatti          2065902
Buick              49625
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge             120395
FIAT               31800
Ferrari           643330
Ford              149995
GMC                71665
Genesis            54550
HUMMER             43130
Honda              47070
Hyundai            68750
Infiniti           88850
Kia                61900
Lamborghini      1500000
Land Rover        199495
Lexus             375000
Lincoln            76650
Lotus              93225
Maserati          182009
Maybach          1382750
Mazda              44015
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         38995
Nissan            149990
Oldsmobile         36795
Plymouth           44625
Pontiac            37610
Porsche           440000
Rolls-Royce       492425
Saab               51330
Scion              31090
Spyker            219990
Subaru             39995
Suzuki             31749
Tesla             134500
Toyota             84325
Volkswagen        101300
Volvo              65700
Name: MSRP, dtype: int64

In [12]:
df.groupby(["Make","Vehicle Style"])["MSRP"].max()

Make   Vehicle Style
Acura  2dr Hatchback     24450
       4dr Hatchback     56670
       4dr SUV           58400
       Coupe            156000
       Sedan             65950
                         ...
Volvo  4dr SUV           65700
       Convertible       41200
       Coupe              2000
       Sedan             59700
       Wagon             61300
Name: MSRP, Length: 287, dtype: int64

In [15]:
convertible_car = df[df["Vehicle Style"]== "Convertible" ]
most_exp = convertible_car.groupby("Make")["MSRP"].max()
print(most_exp)

Make
Alfa Romeo         65900
Aston Martin      320695
Audi              199600
BMW               136900
Bentley           363000
Buick              37065
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge               2000
FIAT               28195
Ferrari           294080
Ford               60110
Honda              37995
Infiniti           62100
Lamborghini       548800
Lexus              68405
Lotus              57950
Maserati          182009
Maybach          1382750
Mazda              32655
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         32599
Nissan             49400
Oldsmobile          2000
Plymouth           44625
Pontiac            32300
Porsche           440000
Rolls-Royce       492000
Saab               51330
Spyker            219990
Toyota             30710
Volkswagen         42745
Volvo              41200
Name: MSRP, dtype: int64

In [18]:
# df[df["Transmission Type"] == ["AUTOMATIC"] ]
df[df["Transmission Type"] == "AUTOMATIC"]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
23,Audi,100,1993,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
27,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
30,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,22,16,3105,2000
31,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [22]:
primium_car = df[df["Engine Fuel Type"] == "premium unleaded (required)"]
most_expensive_premium_cars = primium_car.groupby("Make")["MSRP"].max()
print(most_expensive_premium_cars)

Make
Acura             156000
Alfa Romeo         68400
Aston Martin      320695
Audi              199900
BMW               141200
Bentley           363000
Bugatti          2065902
Buick              40730
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge             120395
Ferrari           643330
Ford              149995
Honda              37995
Infiniti           67050
Lamborghini      1500000
Land Rover        184105
Lexus             375000
Lincoln            51785
Lotus              93225
Maserati          182009
Maybach          1382750
Mazda              32960
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         38995
Nissan            149990
Oldsmobile         35085
Plymouth           44625
Pontiac            35585
Porsche           440000
Rolls-Royce       492425
Saab               48010
Scion              31090
Spyker            219990
Subaru             39995
Toyota             25645
Volkswagen        101300
Volvo              36500
Name: MSRP, dtype: int64

In [25]:
each_car_avg = df.groupby("Make")["MSRP"].mean()
print(each_car_avg)

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissan           2.858343e+04
Oldsmobile       1.154254e+04
Plymouth         3.122902e+03
Pontiac          1.932155e+04
Porsche          1.016224e+05
Rolls-Royce      3.511306e+05
Saab             2.741350e+04
Scion            1.993250e+04
Spyker           2.133233e+05
Subaru           2.482750e+04
Suzuki           1.790721e+04
Tesla            8.525556e+04
Toyota           2.903002e+04
Volkswagen       2.810238e+04
Volvo            2.854116e+04
Name: MSRP, dtype: float64

In [33]:
display(df.dtypes)

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [34]:
display(df.columns)

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [35]:
display(df.axes)

[RangeIndex(start=0, stop=11914, step=1),
 Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
        'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
        'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
        'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
       dtype='object')]

In [36]:
display(df.ndim)

2

In [37]:
display(df.size)

190624

In [38]:
display(df.shape)

(11914, 16)

In [39]:
display(df.values)

array([['BMW', '1 Series M', 2011, ..., 19, 3916, 46135],
       ['BMW', '1 Series', 2011, ..., 19, 3916, 40650],
       ['BMW', '1 Series', 2011, ..., 20, 3916, 36350],
       ...,
       ['Acura', 'ZDX', 2012, ..., 16, 204, 50620],
       ['Acura', 'ZDX', 2013, ..., 16, 204, 50920],
       ['Lincoln', 'Zephyr', 2006, ..., 17, 61, 28995]], dtype=object)

In [41]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [43]:
display(df.tail())

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [45]:
display(df.describe())

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [57]:
display(df.describe(include="all"))

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
count,11914,11914,11914.000000,11911,11845.00000,11884.000000,11914,11914,11908.000000,8172,11914,11914,11914.000000,11914.000000,11914.000000,1.191400e+04
unique,48,915,NaN,10,NaN,NaN,5,4,NaN,71,3,16,NaN,NaN,NaN,NaN
top,Chevrolet,Silverado 1500,NaN,regular unleaded,NaN,NaN,AUTOMATIC,front wheel drive,NaN,Crossover,Compact,Sedan,NaN,NaN,NaN,NaN
freq,1123,156,NaN,7172,NaN,NaN,8266,4787,NaN,1110,4764,3048,NaN,NaN,NaN,NaN
mean,NaN,NaN,2010.384338,NaN,249.38607,5.628829,NaN,NaN,3.436093,NaN,NaN,NaN,26.637485,19.733255,1554.911197,4.059474e+04
std,NaN,NaN,7.579740,NaN,109.19187,1.780559,NaN,NaN,0.881315,NaN,NaN,NaN,8.863001,8.987798,1441.855347,6.010910e+04
min,NaN,NaN,1990.000000,NaN,55.00000,0.000000,NaN,NaN,2.000000,NaN,NaN,NaN,12.000000,7.000000,2.000000,2.000000e+03
25%,NaN,NaN,2007.000000,NaN,170.00000,4.000000,NaN,NaN,2.000000,NaN,NaN,NaN,22.000000,16.000000,549.000000,2.100000e+04
50%,NaN,NaN,2015.000000,NaN,227.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN,26.000000,18.000000,1385.000000,2.999500e+04
75%,NaN,NaN,2016.000000,NaN,300.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN,30.000000,22.000000,2009.000000,4.223125e+04
max,NaN,NaN,2017.000000,NaN,1001.00000,16.000000,NaN,NaN,4.000000,NaN,NaN,NaN,354.000000,137.000000,5657.000000,2.065902e+06

In [56]:
display(df.describe(exclude=["number"]))

,Make,Model,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style
count,11914,11914,11911,11914,11914,8172,11914,11914
unique,48,915,10,5,4,71,3,16
top,Chevrolet,Silverado 1500,regular unleaded,AUTOMATIC,front wheel drive,Crossover,Compact,Sedan
freq,1123,156,7172,8266,4787,1110,4764,3048

In [71]:
display(df.describe(include=["int64"]))
display(df.describe(["numeric" == True]))

print()
display(df.describe(exclude=["int64"]))

               Year   highway MPG      city mpg    Popularity          MSRP
count  11914.000000  11914.000000  11914.000000  11914.000000  1.191400e+04
mean    2010.384338     26.637485     19.733255   1554.911197  4.059474e+04
std        7.579740      8.863001      8.987798   1441.855347  6.010910e+04
min     1990.000000     12.000000      7.000000      2.000000  2.000000e+03
25%     2007.000000     22.000000     16.000000    549.000000  2.100000e+04
50%     2015.000000     26.000000     18.000000   1385.000000  2.999500e+04
75%     2016.000000     30.000000     22.000000   2009.000000  4.223125e+04
max     2017.000000    354.000000    137.000000   5657.000000  2.065902e+06

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
0%,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

,Make,Model,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style
count,11914,11914,11911,11845.00000,11884.000000,11914,11914,11908.000000,8172,11914,11914
unique,48,915,10,NaN,NaN,5,4,NaN,71,3,16
top,Chevrolet,Silverado 1500,regular unleaded,NaN,NaN,AUTOMATIC,front wheel drive,NaN,Crossover,Compact,Sedan
freq,1123,156,7172,NaN,NaN,8266,4787,NaN,1110,4764,3048
mean,NaN,NaN,NaN,249.38607,5.628829,NaN,NaN,3.436093,NaN,NaN,NaN
std,NaN,NaN,NaN,109.19187,1.780559,NaN,NaN,0.881315,NaN,NaN,NaN
min,NaN,NaN,NaN,55.00000,0.000000,NaN,NaN,2.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,170.00000,4.000000,NaN,NaN,2.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,227.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,300.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,1001.00000,16.000000,NaN,NaN,4.000000,NaN,NaN,NaN

In [67]:
display(df.describe(include=["float"]))
print()
display(df.describe(exclude=["float"]))

         Engine HP  Engine Cylinders  Number of Doors
count  11845.00000      11884.000000     11908.000000
mean     249.38607          5.628829         3.436093
std      109.19187          1.780559         0.881315
min       55.00000          0.000000         2.000000
25%      170.00000          4.000000         2.000000
50%      227.00000          6.000000         4.000000
75%      300.00000          6.000000         4.000000
max     1001.00000         16.000000         4.000000

,Make,Model,Year,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
count,11914,11914,11914.000000,11911,11914,11914,8172,11914,11914,11914.000000,11914.000000,11914.000000,1.191400e+04
unique,48,915,NaN,10,5,4,71,3,16,NaN,NaN,NaN,NaN
top,Chevrolet,Silverado 1500,NaN,regular unleaded,AUTOMATIC,front wheel drive,Crossover,Compact,Sedan,NaN,NaN,NaN,NaN
freq,1123,156,NaN,7172,8266,4787,1110,4764,3048,NaN,NaN,NaN,NaN
mean,NaN,NaN,2010.384338,NaN,NaN,NaN,NaN,NaN,NaN,26.637485,19.733255,1554.911197,4.059474e+04
std,NaN,NaN,7.579740,NaN,NaN,NaN,NaN,NaN,NaN,8.863001,8.987798,1441.855347,6.010910e+04
min,NaN,NaN,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,7.000000,2.000000,2.000000e+03
25%,NaN,NaN,2007.000000,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,16.000000,549.000000,2.100000e+04
50%,NaN,NaN,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,26.000000,18.000000,1385.000000,2.999500e+04
75%,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,22.000000,2009.000000,4.223125e+04
max,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,354.000000,137.000000,5657.000000,2.065902e+06

In [62]:
display(df.describe(exclude=["object"]))

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [63]:
display(df.describe(include=["object"]))

,Make,Model,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style
count,11914,11914,11911,11914,11914,8172,11914,11914
unique,48,915,10,5,4,71,3,16
top,Chevrolet,Silverado 1500,regular unleaded,AUTOMATIC,front wheel drive,Crossover,Compact,Sedan
freq,1123,156,7172,8266,4787,1110,4764,3048

In [69]:
df.sample()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
2225,Toyota,Camry Solara,2007,regular unleaded,155.0,4.0,AUTOMATIC,front wheel drive,2.0,NaN,Midsize,Coupe,31,22,2031,20760

In [72]:
df.dropna()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [73]:
df.isnull()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11910,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11911,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11912,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11913,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [75]:
df.notnull()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
11910,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
11911,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
11912,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
11913,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
# changing the name of column

df.rename(columns={'old_name':'new_name'},inplace=True)